version: "3"
services: 
    api:
        container_name: api-node
        restart: always
        build: .
        command: npm run test
        ports:
            - "3050:3010"
        volumes: 
            - .:/app